# Generated by Django 4.2.10 on 2024-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbooks',
            name='dateReturned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
